apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    tke.ai/name: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Release.Name }}    
      tke.ai/name: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Release.Name }}
        tke.ai/name: {{ .Release.Name }}
    spec:
      terminationGracePeriodSeconds: 30
      {{- if .Values.affinity }}
      affinity:
        {{- toYaml .Values.affinity | nindent 8 }}
      {{- end }}
      containers:
      - name: inference
        image: {{ .Values.image }}
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        command: {{ toYaml .Values.command | nindent 12 }}
        ports:
        - containerPort: {{ .Values.service.serverPort }}
          name: metrics
          protocol: TCP
        readinessProbe:
          {{- with .Values.readinessProbe }}
          httpGet:
            path: {{ .httpGet.path }}
            port: {{ .httpGet.port }}
          initialDelaySeconds: {{ .initialDelaySeconds }}
          periodSeconds: {{ .periodSeconds }}
          timeoutSeconds: {{ .timeoutSeconds }}
          successThreshold: {{ .successThreshold }}
          failureThreshold: {{ .failureThreshold }}
          {{- end }}
        lifecycle: {{ toYaml .Values.lifecycle | nindent 10 }}
        securityContext:
          privileged: true
          capabilities:
            add: ["IPC_LOCK"]
        env:
        {{- with .Values.env }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
        volumeMounts:
        - mountPath: /dev/shm
          name: dshm
        {{- range .Values.volumeMounts }}
        - name: {{ .name }}
          mountPath: {{ .mountPath }}
        {{- end }}
      volumes:
      - name: dshm
        emptyDir:
          medium: Memory
      {{- with .Values.volumes }}
      {{- toYaml . | nindent 6 }}
      {{- end }}