apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    tke.ai.playbook/app-name: {{ .Release.Name }}
spec:
  podTargetLabels:
    - app.kubernetes.io/name
    - tke.ai.playbook/app-name
  jobLabel: app.kubernetes.io/name
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Release.Name }}
      tke.ai.playbook/app-name: {{ .Release.Name }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  endpoints:
    - port: metrics
      interval: 5s
      path: /metrics
