apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ .Release.Namespace | quote }}
  name: tke-ai-sglang-dashboard
  labels:
    app: {{ .Release.Name }}-grafana
    dashboard: sglang-dashboard
data:
  sglang-dashboard.json: |-
    {{ .Files.Get "dashboards/sglang-dashboard.json" | nindent 4 }}