apiVersion: v2
name: lws
description: A general-purpose AI/ML inference workload that supports the distributed execution of large language models (LLM).

type: application

# This is the chart version. 
version: 0.1.0

home: https://github.com/kubernetes-sigs/lws

kubeVersion: '>=1.27.0-0'

# This is the version number of the application being deployed. 
appVersion: "v0.5.0"
